library(dplyr)
consumption_data = read.table("exdata_data_household_power_consumption/household_power_consumption.txt",header = TRUE,sep = ";")
filter_data = consumption_data %>% filter(Date == "1/2/2007"|Date == "2/2/2007")
filter_data$Date = as.Date(filter_data$Date, format = "%d/%m/%Y")
filter_data$Time = strptime(filter_data$Time, format = "%H:%M:%S")
filter_data[1:1440,"Time"] = format(filter_data[1:1440,"Time"],"2007-02-01 %H:%M:%S")
filter_data[1441:2880,"Time"] = format(filter_data[1441:2880,"Time"],"2007-02-02 %H:%M:%S")

png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(filter_data$Time,as.numeric(filter_data$Global_active_power),xlab = "",ylab = "Global Active Power",type = "l")
plot(filter_data$Time,as.numeric(filter_data$Voltage),xlab = "datetime",ylab = "Voltage",type = "l")
plot(filter_data$Time,as.numeric(filter_data$Sub_metering_1),xlab = "",ylab = "Energy sub metering",type = "n")
lines(filter_data$Time,as.numeric(filter_data$Sub_metering_1))
lines(filter_data$Time,as.numeric(filter_data$Sub_metering_2),col = "red")
lines(filter_data$Time,as.numeric(filter_data$Sub_metering_3),col= "blue")
legend("topright",lty=1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex = 0.5)
plot(filter_data$Time,as.numeric(filter_data$Global_reactive_power),xlab = "datetime",ylab = "Global_reactive_power",type = "l")
dev.off()
